### ISSUE TITLE
Honeypot token source code?

### ISSUE THREAD

**Issue by Homiekoh** [FaydSpeare/blockchain-rug-pull#1]
Hello, is code for honeypot token? If so is it on Binance smart chain? Thanks! 
PS: I don’t know how to code! Yet at least.

**Comment by FaydSpeare** [comment]
Ah this isn't the honeypot token, what made you think that? 😅

**Comment by Homiekoh** [comment]
I really appreciate your reply! 😂 I’m looking for the honeypot source code, I just searched “honeypot” on GitHub and boy lots of codes showed up... anyway any idea where I can get the source code for free? I would appreciate it! 🙏🏾

**Comment by Homiekoh** [comment]
> Ah this isn't the honeypot token, what made you think that? 😅

😂
